import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/Components/UI/Navbar'
import Footer from '@/Components/UI/Footer'
import { ToastContainer } from 'react-toastify'
import { Providers } from '@/redux/Provider'


export const metadata: Metadata = {
  title: 'My Hair Salon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>
    <html lang="en">
      <body>
        <Providers>
         
      <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
        />
        {/**@ts-ignore */}
        <Navbar />
        {children}
        <Footer />
        </Providers>
        </body>
    </html>
    </>


}
