import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/Components/UI/Navbar'
import Footer from '@/Components/UI/Footer'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'


export const metadata: Metadata = {
  title: 'My Hair Salon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>
    <html lang="en">
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>  
      <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
        />
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
    </>


}
